[package]
name = "ramag-tool-object-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Ramag 云对象存储工具 UI"

[lints]
workspace = true

[dependencies]
ramag-domain = { workspace = true }
ramag-app = { workspace = true }
ramag-ui = { workspace = true }
gpui-kit = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
tracing = { workspace = true }
rfd = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
gpui-kit = { workspace = true, features = ["test-support"] }
