[package]
name = "ramag-infra-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Ramag API 测试工具的 HTTP/gRPC 基础设施预研与驱动"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
prost-reflect = { workspace = true }
ramag-domain = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tonic-reflection = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }

[dev-dependencies]
tonic = { workspace = true, features = ["router"] }
tonic-reflection = { workspace = true, features = ["server"] }
