[package]
name = "ramag-tool-container"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Ramag Docker 与 Kubernetes 容器管理工具"

[lints]
workspace = true

[dependencies]
ramag-app = { workspace = true }
ramag-domain = { workspace = true }
ramag-ui = { workspace = true }
gpui-kit = { workspace = true }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
